# Generated by Django 4.0.5 on 2022-06-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=128, verbose_name='Ip')),
                ('int_prov', models.CharField(max_length=100, verbose_name='Int_prov')),
                ('org', models.CharField(max_length=100, verbose_name='Org')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('region_name', models.CharField(max_length=100, verbose_name='Region name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('zip', models.CharField(max_length=20, verbose_name='ZIP')),
                ('lat', models.FloatField(verbose_name='Lat')),
                ('lon', models.FloatField(verbose_name='Lon')),
            ],
        ),
    ]
