# Generated by Django 4.0.5 on 2022-06-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipinfo',
            name='status',
            field=models.CharField(default='success', max_length=20, verbose_name='Status'),
        ),
    ]
